# Camera intrinsic parameters
camera_face:
  fx: 607.99951171875
  fy: 607.8468627929688
  cx: 325.8788757324219
  cy: 233.54624938964844
  width: 640  
  height: 480

# Transform parameters
trans_x: 0.011611
trans_y: 0.004437
trans_z: 0.000108

# Rotation parameters
rotation:
  # r1: ['y', -1.5708]  # Y축 기준 -90도 회전 (카메라 Z축을 로봇 X축으로)
  # r2: ['z', 3.1416]   # Z축 기준 180도 회전 (카메라 X축을 로봇 -Y축으로)
  # r3: ['x', 3.1416]

  # r1: ['y', -1.5708]  # Y축 기준 -90도 회전 (카메라 Z축을 로봇 X축으로)
  # r2: ['x', 3.1416]   # X축 기준 180도 회전
  # r3: ['z', -1.5708]  # Z축 기준 -90도 회전

  r1: ['x', 3.1416]
  r2: ['y', -0.1745]
  r3: ['z', 0]